# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZTCustomNavigationBar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'SDWebImage', '~> 3.7.6'

    #UI
    pod 'SDCycleScrollView','~> 1.64'
  # Pods for ZTCustomNavigationBar

  target 'ZTCustomNavigationBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZTCustomNavigationBarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
